src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields="email", message="There is already an account with this email")
 * @UniqueEntity(fields="username", message="This username is already taken")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true, nullable=false)
     */
    private string $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private string $password;

    private $plainPassword;

    /**
     * @ORM\Column(type="string", length=50, unique=true, nullable=false)
     * @Assert\NotBlank(message="Username must not be blank")
     * @Assert\Length(
     *      min=5,
     *      max=40,
     *      minMessage="Username must be at least {{ limit }} characters long",
     *      maxMessage="Username cannot be longer than {{ limit }} characters"
     * )
     * @Assert\Regex(
     *      pattern="/^[\p{L}0-9\s!&.:]+$/u",
     *      message="Username can only contain letters, numbers, and spaces."
     * )
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="user", cascade={"remove"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Recipes::class, mappedBy="user")
     */
    private $recipes;

    /**
     * @ORM\ManyToMany(targetEntity=Recipes::class, mappedBy="likedUsers")
     * @ORM\JoinTable(name="user_likes",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="recipe_id", referencedColumnName="id")}
     * )
     */
    private $likedRecipes;

    public function __construct() {
        $this->roles = ['ROLE_USER'];
        $this->comments = new ArrayCollection();
        $this->recipes = new ArrayCollection();
        $this->likedRecipes = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getUsername(); // return username
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     * @return string the hashed password for this user
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
         $this->plainPassword = null;
    }

    // This property will not be persisted to the database:
    // it's just a temporary property that we can use during registration, to store the plain password.
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;
        return $this;
    }

    /**
     * This method generates the URI for the user's avatar using the ui-avatars.com service.
     * It allows specifying the display name and avatar size.
     *
     * @param int $size The size of the avatar image (default is 35).
     *
     * @return string The URI for the user's avatar image.
     */
    public function getAvatarUrl(int $size = 35): string
    {
        return 'https://ui-avatars.com/api/?' . http_build_query([
                'name' => $this->getDisplayName(),
                'size' => $size,
        ]);
    }

    public function getDisplayName(): string
    {
        return $this->username ?? $this->getEmail();
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Recipes>
     */
    public function getRecipes(): Collection
    {
        return $this->recipes;
    }

    public function addRecipe(Recipes $recipe): self
    {
        if (!$this->recipes->contains($recipe)) {
            $this->recipes[] = $recipe;
            $recipe->setUser($this);
        }

        return $this;
    }

    public function removeRecipe(Recipes $recipe): self
    {
        if ($this->recipes->removeElement($recipe)) {
            // set the owning side to null (unless already changed)
            if ($recipe->getUser() === $this) {
                $recipe->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Recipes>
     */
    public function getLikedRecipes(): Collection
    {
        return $this->likedRecipes;
    }

    public function addLikedRecipe(Recipes $likedRecipe): self
    {
        if (!$this->likedRecipes->contains($likedRecipe)) {
            $this->likedRecipes[] = $likedRecipe;
        }

        return $this;
    }

    public function removeLikedRecipe(Recipes $likedRecipe): self
    {
        $this->likedRecipes->removeElement($likedRecipe);

        return $this;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/jpg" href="{{ asset('images/favicon.ico') }}" />
        <title>{% block title %}Umami{% endblock %}</title>

        {# data-route : Initialize the variable, defaulting to null if not set #}
        {% set pageRoute = pageRoute ?? null %}

        {#  Include jQuery via CDN  #}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
            {# Style Entrypoint and the directry confirmed in webpack.config.js #}
            <link rel="stylesheet" href="{{ asset('build/base-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/header-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/footer-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/home-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/about-us.css') }}">
            <link rel="stylesheet" href="{{ asset('build/notifications-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/card-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/form-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/button-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/show-recipe-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/recipe-form-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/recipes-dashboard-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/cuisines-dashboard-styles.css') }}">
            <link rel="stylesheet" href="{{ asset('build/user-profile.css') }}">
            <link rel="stylesheet" href="{{ asset('build/recipes-filters.css') }}">
            <link rel="stylesheet" href="{{ asset('build/legal-pages.css') }}">
            <link rel="stylesheet" href="{{ asset('build/contact-form.css') }}">
            <link rel="stylesheet" href="{{ asset('build/delete-confirmations.css') }}">
            <link rel="stylesheet" href="{{ asset('fonts/fontawesome-free-6.4.2-web/css/all.css') }}" title="Font Awesome Icons">
        {% endblock %}

        {% block javascripts %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
            <script src="{{ asset('js/base-functions.js') }}"></script>
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>

    {#  Use pageRoute to defined each page design path  #}
    <body data-route="{{ pageRoute }}">
        {% include 'header.html.twig' %}
        <main id="mainContent">
            {# Flash messages for success/error/warning  #}
            {% for flash in app.flashes('success') %}
                <div class="alert-success-message alert-flash" role="alert">{{ flash }}</div>
            {% endfor %}
            {% for flash in app.flashes('error') %}
                <div class="alert-danger-message alert-flash" role="alert">{{ flash }}</div>
            {% endfor %}
            {% for flash in app.flashes('warning') %}
                <div class="alert-warning-message alert-flash" role="alert">{{ flash }}</div>
            {% endfor %}
            {# Flash messages for email verification error  #}
            {% for flash_error in app.flashes('verify_email_error') %}
                <div class="alert-danger-message alert-flash" role="alert">{{ flash_error }}</div>
            {% endfor %}

            <div id="flash-message-container">
                {% for flashMessage in app.flashes('success') %}
                    <div class="alert-success-message alert-flash" role="alert">{{ flashMessage }}</div>
                {% endfor %}
            </div>

            {% block body %}
            {% endblock %}
        </main>
        {% include 'footer.html.twig' %}
    </body>
</html>

templates/footer.html.twig
{# Scroll up arrow #}
<a id="back-to-top" href="#top"><i class="fas fa-chevron-up"></i></a>

<footer id="footerContent" class="footer">
    <div class="container">
        <div class="footer-columns">

            {# Umami Logo and Description Column #}
            <div class="footer-column">
                <h3 class="footer-title">About us</h3>
                <a href="{{ path('home') }}" class="footer-logo-link">
                    <img src="{{ asset('images/umami-logos_white_half.png') }}" alt="Umami Logo">
                </a>
                <p>Global recipes, culinary passion, food lovers unite.</p>
            </div>

            {# Contact Information Column #}
            <div class="footer-column">
                <h3 class="footer-title">Contact Information</h3>
                <address>
                    <p>Address: Paris, FR</p>
                    <p>Phone:  (06) 12-34-56-78</p>
                    <p>Email: <a href="mailto:customer_service@umami.com">customer_service@umami.com</a></p>
                </address>
            </div>

            {# Our Policies Column #}
            <div class="footer-column">
                <h3 class="footer-title">Our policies</h3>
                <a href="{{ path('privacy_policy') }}" class="footer-link">
                    <p>Privacy Policy</p>
                </a>
                <a href="{{ path('legal_notice') }}" class="footer-link">
                    <p>Legal Information</p>
                </a>
                {# Contact Us Link #}
                <a href="{{ path('app_contact_us') }}" class="footer-link">
                    <p>Contact Us</p>
                </a>
            </div>
        </div>

        <div class="footer-credits">
            <p>&copy; 2024 UMAMI. All rights reserved.</p>
        </div>
    </div>
</footer>

templates/header.html.twig
<header class="header">
    <div class="topbar">
        <div class="logo">
            <a href="{{ path('home') }}">
                <img src="{{ asset('images/umami-blue-small.png') }}" alt="Umami Logo" aria-hidden="true">
            </a>
        </div>
        <nav class="menu topnav" id="myTopnav" role="navigation">
            {# Main Navigation Links #}
            <a href="{{ path('about_us') }}" class="menu-item">About</a>
            <a href="{{ path('app_contact_us') }}" class="menu-item">Contact</a>

            {# Admin-specific Navigation Links (if user is an admin) #}
            {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('admin_dashboard') }}" class="menu-item">Admin</a>
            {% endif %}

            {# User-specific Navigation Links #}
            {% if is_granted('IS_AUTHENTICATED_REMEMBERED') and app.user.displayName is not same as(app.user.email) %}
                <a href="{{ path('cuisines') }}" class="menu-item">Cuisines</a>
                <a href="{{ path('list_recipes') }}" class="menu-item">About Recipes</a>
                <a href="{{ path('logout') }}" class="menu-item">Log Out</a>
                <a href="{{ path('user_edit') }}" class="menu-item menu-button-box" aria-label="{{ app.user.displayName }} Avatar">
                    <img src="{{ app.user.avatarUrl }}" alt="{{ app.user.displayName }} Avatar">
                </a>
            {% elseif is_granted('IS_AUTHENTICATED_REMEMBERED') and app.user.displayName is same as(app.user.email) %}
                <a href="{{ path('list_recipes') }}" class="menu-item">About Recipes</a>
                <a href="{{ path('logout') }}" class="menu-item">Log Out</a>
                <i class="fa-regular fa-user" aria-hidden="true"></i>
            {% else %}
                <a href="{{ path('login') }}" class="menu-item">Log In</a>
                <a href="{{ path('register') }}" class="menu-item">Sign Up</a>
            {% endif %}

            {#  Search Icon #}
            <a href="{{ path('app_recipes_all_filters') }}" class="menu-item menu-button-box" aria-label="Search">
                <i class="fa fa-search" aria-hidden="true"></i>
            </a>

            {# Dark Mode Toggle #}
            <a id="darkModeToggle" class="menu-item menu-button-box" aria-label="Toggle light/dark mode">
                <i class="fa-solid fa-circle-half-stroke" aria-hidden="true"></i>
            </a>

            {# Responsive Navigation Toggle #}
            <a href="#" class="icon" id="toggleNav" aria-label="Toggle Navigation">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </a>
        </nav>
    </div>
    <div class="baseline">
        <img class="baseline-name text-center" src="{{ asset('images/umami-blue.png') }}" alt="UMAMI Logo">
        <span class="baseline-slogan">Savor the Flavor</span>
    </div>
</header>